### 配置指定服务
POST /services HTTP/1.1
Host: localhost:10101
User-Agent: curl/8.0.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

name=example_service&url=http://httpbin.org

### 查看指定服务
GET http://localhost:10101/services/example_service

### 查看所有服务
GET http://localhost:10101/services

### 创建路由
POST /services/example_service/routes HTTP/1.1
Host: localhost:10101
User-Agent: curl/8.0.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

paths[]=/mock&name=example_route

### 查看路由配置
GET http://localhost:10101/services/example_service/routes/example_route

### 访问 API
GET http://localhost:18000/mock/anything

### 全局启用 cors 插件
POST /plugins/ HTTP/1.1
Host: localhost:10101
User-Agent: curl/8.0.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

name=cors&config.origins=*&config.methods=GET&config.methods=POST&config.headers=Accept&config.headers=Accept-Version&config.headers=Content-Length&config.headers=Content-MD5&config.headers=Content-Type&config.headers=Date&config.headers=X-Auth-Token&config.exposed_headers=X-Auth-Token&config.credentials=true&config.max_age=3600&config.preflight_continue=true

### 更新插件
DELETE /plugins/e972bc37-974c-4411-bf87-e730c27891d6 HTTP/1.1
Host: localhost:10101
User-Agent: curl/8.0.1
Accept: */*
Content-Type: application/x-www-form-urlencoded