# 日志项配置
log:
  # 是否每次启动新建log文件
  force-new: false
  # 日志等级
  #   trace debug info warn error
  level: 'debug'
  # 日志存活时间，到期新建log文件
  aging: 24h
  # 是否开启控制台颜色
  colorful: true

# minecraft 相关设置
minecraft:
  # 版本设置
  version:
    # 启动时加载的版本
    # 为空则启动时自动加载默认版本
    entry-list: ['1.21.1']
    # 是否自动加载其他请求的版本
    # 如果关闭, API 将在收到未配置版本时直接返回空值
    auto-load: true
  # 相关资源设置
  resource:
    # 在物品工具提示等地方应该使用哪种语言
    # https://minecraft.fandom.com/wiki/Language
    language: en_us
    # 绘制所使用的字体，应位于 config/fonts 文件夹下
    # 如果指定字体不存在，将自动下载默认字体
    font: Minecraft.ttf
  # BlessingSkin 皮肤站链接 (若配置则按顺序调用加载皮肤)
  # 注意: 使用需皮肤站开启 legacy-api(传统皮肤加载方式)
  blessing-skin:
#    - https://skin.mualliance.ltd
    - https://skin.fjmua.cn

api:
  player-list:
    # 单行展示的最大玩家数
    single-column-limit: 20
    # 顶部文本, 留空则跳过绘制
    header-text:
      - "&aOnline Players ({OnlinePlayers}/100)"
    # 底部文本, 留空则跳过绘制
    footer-text:
      - "&e{Host}"