# 日志项配置
log:
  # 是否每次启动新建log文件
  force-new: false
  # 日志等级
  #   trace debug info warn error
  level: 'debug'
  # 日志存活时间，到期新建log文件
  aging: 24h
  # 是否开启控制台颜色
  colorful: true

# minecraft 相关设置
minecraft:
  # 版本设置
  version:
    # 启动时加载的版本
    enable: ['1.20.1']
    # 是否自动加载其他请求的版本
    # 如果关闭, API 将在收到未配置版本时直接返回空值
    auto-load: true