// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get_player_list": {
            "post": {
                "description": "获取在线玩家列表的图像. 如果传入玩家为空，则返回错误码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "获取在线玩家列表的图像",
                "parameters": [
                    {
                        "description": "玩家列表请求数据",
                        "name": "playerListRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PlayerListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/http.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "失败响应",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "http.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {}
            }
        },
        "model.PlayerListRequest": {
            "type": "object",
            "required": [
                "version"
            ],
            "properties": {
                "entry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PlayerListRequestEntry"
                    }
                },
                "options": {
                    "$ref": "#/definitions/model.PlayerListRequestOptions"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.PlayerListRequestEntry": {
            "type": "object",
            "required": [
                "entry",
                "ping",
                "player-uuid"
            ],
            "properties": {
                "entry": {
                    "type": "string"
                },
                "ping": {
                    "type": "integer"
                },
                "player-uuid": {
                    "type": "string"
                }
            }
        },
        "model.PlayerListRequestOptions": {
            "type": "object",
            "properties": {
                "show-avatar": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
